[package]
name = "Ron_Way"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
toml = "0.5"
ron = "0.7"
regex = "1"

[[bin]]
name = "Ron_Way"
path = "src/main.rs"